name: Construir imagen Docker 

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: write

jobs:
  construir-imagen-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Listar archivos del repositorio
        run: ls -la

      - name: Verificar que exista el Dockerfile
        run: test -f Dockerfile

      - name: Cerrar sesión en Docker (sino hay error)
        run: docker logout

      - name: Iniciar sesión en GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Construir imagen Docker del backend
        run: docker build --no-cache --progress=plain -t ghcr.io/valenh5/backend---uavdocx/backend-app:pr-${{ github.event.pull_request.number }} .

      - name: Subir imagen Docker a GHCR
        run: docker push ghcr.io/valenh5/backend---uavdocx/backend-app:pr-${{ github.event.pull_request.number }}
